numpy(넘파이) 기초 정리 (https://doorbw.tistory.com/171) 中

6-3. 통계 함수
통계 함수를 통해 array의 합이나 평균등을 구할 때,

추가로 axis라는 인자에 대한 값을 지정하여 열 또는 행의 합 또는 평균등을 구할 수 있다.

In [4]:
import numpy as np

In [ ]:
#랜덤함수로 5x3의 array 생성
arr1 = np.random.randn(5,3)
arr1

array([[-0.4115981 , -0.3727125 , -0.53993059],
       [ 0.45750611,  0.19507641, -0.22388999],
       [ 0.23670419,  1.72440227, -2.17679308],
       [-0.39888263, -0.2486265 ,  0.28297756],
       [ 0.62513947,  0.43485455,  0.11309988]])

In [ ]:
# 전체 성분의 합을 계산
np.sum(arr1)

-0.3026729587256184

+ 행렬은 2차원 텐서
+ [행, 열]의 axis는 각각 [0, 1]
+ 헷갈리면 행 → 0 열 ↓1

In [ ]:
# 열 간의 합을 계산
np.sum(arr1, axis=1)

array([-1.32424119,  0.42869253, -0.21568663, -0.36453157,  1.1730939 ])

In [ ]:
# 행 간의 합을 계산
np.sum(arr1, axis=0)

array([ 0.50886903,  1.73299423, -2.54453622])

In [ ]:
# 전체 성분의 평균을 계산
np.mean(arr1)

-0.02017819724837456

In [ ]:
# 행 간의 평균을 계산
np.mean(arr1, axis=0)

array([ 0.10177381,  0.34659885, -0.50890724])

In [ ]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)
np.std(arr1), np.var(arr1)

(0.7980370504555134, 0.6368631338997357)

예제

어느 학생 집단에서

+ 주당 도서관에 있는 시간을 x1
+ 패턴인식 과목 점수를 x2
+  주당 강의 빼먹는 시간을 x3

이라 하고 다음과 같은 데이터를 수집하였다.


-> (x1, x2), (x2, x3)에 대한 상관계수를 알아보아라.

arr2 = np.array(
  [35, 11, 0.5],
  [5, 12, 0],
  [0, 5, 10],
  [20, 9, 4.5],
  [15, 8, 5])

  -> 평균, 분산, 공분산, 상관계수

In [ ]:
# 데이터
arr2 = np.array([
  [35, 11, 0.5],
  [5, 12, 0],
  [0, 5, 10],
  [20, 9, 4.5],
  [15, 8, 5]])
# 평균
arrmean=np.mean(arr2, axis=0)
arrmean

array([15.,  9.,  4.])

In [ ]:
# 분산 (n으로 나눔)
arrvar=np.var(arr2, axis=0)
arrvar

array([150. ,   6. ,  13.1])

In [ ]:
# 공분산
arrx1 = arr2[:,0]
arrx2 = arr2[:,1]
arrx3 = arr2[:,2]
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기(add, subtract, multiply, divide)
# 공분산 (x1, x2), (x2, x3)
# (xi-xmean)의 값을 곱해야 하므로 subtract와 ones로 구현
c12=(np.sum(np.multiply(
  np.subtract(arrx1,arrmean[0]*np.ones(5)),
  np.subtract(arrx2,arrmean[1]*np.ones(5))
  )))/(5-1)
c23=(np.sum(np.multiply(
  np.subtract(arrx2,arrmean[1]*np.ones(5)),
  np.subtract(arrx3,arrmean[2]*np.ones(5))
  )))/(5-1)
c12, c23

(17.5, -11.0)

In [ ]:
#sqrt를 쓰기 위해서 math 라이브러리 사용
import math
r12=c12/math.sqrt(arrvar[0])/math.sqrt(arrvar[1])
r23=c23/math.sqrt(arrvar[1])/math.sqrt(arrvar[2])
r12, r23

(0.5833333333333334, -1.2407417956860893)

문제의 답은 0.4667, -0.9926이지만,

numpy 라이브러리 함수 variance가 n-1이 아니라 n으로 나누는 차이가 있으므로

계산방법은 적절했다고 볼 수 있다.

In [9]:
arr3 = np.array([
  [77, 85, 48, 94, 80, 60, 65, 96, 70, 86, 69, 82],
  [78.2, 82.1, 60.3, 91.5, 84.6, 70.8, 68.4, 90.8, 75.0, 92.5, 61.8, 80.1]])
# 평균
arrmean=np.mean(arr3, axis=1)


# 분산 (n으로 나눔)
arrvar=np.var(arr3, axis=1)
arrmean, arrvar

(array([76.        , 78.00833333]), array([183.66666667, 112.49076389]))