+ row vector x[0, :]
+ column vector x[:, 1]
+ transpose .T

In [8]:
import numpy as np

In [ ]:
data = np.array([
  [2, 2, 4],
  [3, 4, 6],
  [5, 4, 2],
  [6, 6, 4]
])
"""
datam = np.mean(data, axis=0)
datamm = np.array([
  np.subtract(data[:,0], datam[0]),
  np.subtract(data[:,1], datam[1]),
  np.subtract(data[:,2], datam[2])
])
datammm = np.swapaxes(datamm,0,1)**2
datam4 = np.mean(datammm, axis=0)
dataOut = np.zeros(shape=(3,3))
for i in range(0,3):
  for j in range(0,3):
    dataOut[i,j]=datam4[i]*datam4[j]
print(dataOut)
"""

datam = np.mean(data, axis=0)
datamu = np.array([
  np.subtract(data[:,0], datam[0]),
  np.subtract(data[:,1], datam[1]),
  np.subtract(data[:,2], datam[2])
])
dataOut = np.multiply(np.dot(datamu, datamu.T), 1/3)
print(dataOut)

dataOutCmp = np.cov(np.swapaxes(data,0,1))
print(dataOutCmp)

[[ 3.33333333  2.66666667 -1.33333333]
 [ 2.66666667  2.66666667  0.        ]
 [-1.33333333  0.          2.66666667]]
[[ 3.33333333  2.66666667 -1.33333333]
 [ 2.66666667  2.66666667  0.        ]
 [-1.33333333  0.          2.66666667]]


In [ ]:
def cova(data):
  print("*input matrix <class = %d>" % (len(data.T)))
  print(data)
  datamean = np.mean(data, axis=0)
  datamu = np.subtract(data, datamean)
  dataOut = np.multiply(np.dot(datamu.T, datamu), 1/(len(data)-1))
  print("==> covariance matrix")
  print(dataOut)
  return dataOut

In [ ]:
cova(data)

*input matrix <class = 3>
[[2 2 4]
 [3 4 6]
 [5 4 2]
 [6 6 4]]
==> covariance matrix
[[ 3.33333333  2.66666667 -1.33333333]
 [ 2.66666667  2.66666667  0.        ]
 [-1.33333333  0.          2.66666667]]


array([[ 3.33333333,  2.66666667, -1.33333333],
       [ 2.66666667,  2.66666667,  0.        ],
       [-1.33333333,  0.        ,  2.66666667]])

*3.15 정리

# numpy(넘파이) 기초 정리 (https://doorbw.tistory.com/171) 中

6-3. 통계 함수
통계 함수를 통해 array의 합이나 평균등을 구할 때,

추가로 axis라는 인자에 대한 값을 지정하여 열 또는 행의 합 또는 평균등을 구할 수 있다.

In [ ]:
#랜덤함수로 5x3의 array 생성
arr1 = np.random.randn(5,3)
arr1

array([[-0.4115981 , -0.3727125 , -0.53993059],
       [ 0.45750611,  0.19507641, -0.22388999],
       [ 0.23670419,  1.72440227, -2.17679308],
       [-0.39888263, -0.2486265 ,  0.28297756],
       [ 0.62513947,  0.43485455,  0.11309988]])

In [ ]:
# 전체 성분의 합을 계산
np.sum(arr1)

-0.3026729587256184

+ 행렬은 2차원 텐서
+ [행, 열]의 axis는 각각 [0, 1]
+ 헷갈리면 행 → 0 열 ↓1

In [ ]:
# 열 간의 합을 계산
np.sum(arr1, axis=1)

array([-1.32424119,  0.42869253, -0.21568663, -0.36453157,  1.1730939 ])

In [ ]:
# 행 간의 합을 계산
np.sum(arr1, axis=0)

array([ 0.50886903,  1.73299423, -2.54453622])

In [ ]:
# 전체 성분의 평균을 계산
np.mean(arr1)

-0.02017819724837456

In [ ]:
# 행 간의 평균을 계산
np.mean(arr1, axis=0)

array([ 0.10177381,  0.34659885, -0.50890724])

In [ ]:
# 전체 성분의 표준편차, 분산, 최소값, 최대값 계산(std, var, min, max)
np.std(arr1), np.var(arr1)

(0.7980370504555134, 0.6368631338997357)

예제

어느 학생 집단에서

+ 주당 도서관에 있는 시간을 x1
+ 패턴인식 과목 점수를 x2
+  주당 강의 빼먹는 시간을 x3

이라 하고 다음과 같은 데이터를 수집하였다.


-> (x1, x2), (x2, x3)에 대한 상관계수를 알아보아라.

arr2 = np.array(
  [35, 11, 0.5],
  [5, 12, 0],
  [0, 5, 10],
  [20, 9, 4.5],
  [15, 8, 5])

  -> 평균, 분산, 공분산, 상관계수

In [ ]:
# 데이터
arr2 = np.array([
  [35, 11, 0.5],
  [5, 12, 0],
  [0, 5, 10],
  [20, 9, 4.5],
  [15, 8, 5]])
# 평균
arrmean=np.mean(arr2, axis=0)
arrmean

array([15.,  9.,  4.])

In [ ]:
# 분산 (n으로 나눔)
arrvar=np.var(arr2, axis=0)
arrvar

array([150. ,   6. ,  13.1])

In [ ]:
# 공분산
arrx1 = arr2[:,0]
arrx2 = arr2[:,1]
arrx3 = arr2[:,2]
# 두 개의 array에 대해 동일한 위치의 성분끼리 연산 값을 계산하기(add, subtract, multiply, divide)
# 공분산 (x1, x2), (x2, x3)
# (xi-xmean)의 값을 곱해야 하므로 subtract와 ones로 구현
c12=(np.sum(np.multiply(
  np.subtract(arrx1,arrmean[0]*np.ones(5)),
  np.subtract(arrx2,arrmean[1]*np.ones(5))
  )))/(5-1)
c23=(np.sum(np.multiply(
  np.subtract(arrx2,arrmean[1]*np.ones(5)),
  np.subtract(arrx3,arrmean[2]*np.ones(5))
  )))/(5-1)
c12, c23

(17.5, -11.0)

In [ ]:
#sqrt를 쓰기 위해서 math 라이브러리 사용
import math
r12=c12/math.sqrt(arrvar[0])/math.sqrt(arrvar[1])
r23=c23/math.sqrt(arrvar[1])/math.sqrt(arrvar[2])
r12, r23

(0.5833333333333334, -1.2407417956860893)

문제의 답은 0.4667, -0.9926이지만,

numpy 라이브러리 함수 variance가 n-1이 아니라 n으로 나누는 차이가 있으므로

계산방법은 적절했다고 볼 수 있다.

In [ ]:
arr3 = np.array([
  [77, 85, 48, 94, 80, 60, 65, 96, 70, 86, 69, 82],
  [78.2, 82.1, 60.3, 91.5, 84.6, 70.8, 68.4, 90.8, 75.0, 92.5, 61.8, 80.1]])
# 평균
arrmean=np.mean(arr3, axis=1)


# 분산 (n으로 나눔)
arrvar=np.var(arr3, axis=1)
arrmean, arrvar

(array([76.        , 78.00833333]), array([183.66666667, 112.49076389]))

In [ ]:
cova(arr2)
cova(arr3.T)
print("***compare***")
print(np.cov(arr2.T))
print(np.cov(arr3))
print(17.5/math.sqrt(187.5)/math.sqrt(7.5))
print(np.var(arr3, axis=1))
print(200.3636*11)
print(183.6666*12)

*input matrix <class = 3>
[[35.  11.   0.5]
 [ 5.  12.   0. ]
 [ 0.   5.  10. ]
 [20.   9.   4.5]
 [15.   8.   5. ]]
==> covariance matrix
[[187.5    17.5   -29.375]
 [ 17.5     7.5   -11.   ]
 [-29.375 -11.     16.375]]
*input matrix <class = 2>
[[77.  78.2]
 [85.  82.1]
 [48.  60.3]
 [94.  91.5]
 [80.  84.6]
 [60.  70.8]
 [65.  68.4]
 [96.  90.8]
 [70.  75. ]
 [86.  92.5]
 [69.  61.8]
 [82.  80.1]]
==> covariance matrix
[[200.36363636 142.53636364]
 [142.53636364 122.71719697]]
***compare***
[[187.5    17.5   -29.375]
 [ 17.5     7.5   -11.   ]
 [-29.375 -11.     16.375]]
[[200.36363636 142.53636364]
 [142.53636364 122.71719697]]
0.4666666666666666
[183.66666667 112.49076389]
2203.9996
2203.9991999999997


In [12]:
data1 = np.array([
  [10, 15],
  [20, 10],
  [30, 25],
  [40, 20]
])
cova(data1)

data2 = np.array([
  [1,2],
  [2,4],
  [4,4],
  [5,4],
  [5,6],
  [6,5],
  [8,7],
  [9,8]
])
cova(data2)

np.cov(np.swapaxes(data2,0,1))

*input matrix <class = 2>
[[10 15]
 [20 10]
 [30 25]
 [40 20]]
==> covariance matrix
[[166.66666667  50.        ]
 [ 50.          41.66666667]]
*input matrix <class = 2>
[[1 2]
 [2 4]
 [4 4]
 [5 4]
 [5 6]
 [6 5]
 [8 7]
 [9 8]]
==> covariance matrix
[[7.42857143 4.85714286]
 [4.85714286 3.71428571]]


array([[7.42857143, 4.85714286],
       [4.85714286, 3.71428571]])